### ISSUE TITLE
Fails to install in PHP 7.4.6

### ISSUE THREAD

**Issue by josev814** [flaupretre/pecl-pcs#12]
When attempting to install in Debian Buster PHP 7.4 pcs-1.3.3 fails to install.  I've tested in PHP 7.2 and 7.3 and they install correctly.
https://github.com/flaupretre/pecl-pcs/blob/84470b9d2d1b25e2171417bf076f553e65d23b39/src/PCS_Loader.c#L248

The error output is:
```
/tmp/pear/temp/pcs/src/PCS_Stream.c:35:2: note: (near initialization for 'pcs_dirops.read')
In file included from /tmp/pear/temp/pcs/php_pcs.c:92:
/tmp/pear/temp/pcs/src/PCS_Loader.c: In function 'PCS_Loader_loadNode':
/tmp/pear/temp/pcs/src/PCS_Loader.c:248:21: error: 'union <anonymous>' has no member named 'fd'; did you mean 'fp'?
  file_handle.handle.fd = 0;
                     ^~
                     fp
make: *** [Makefile:216: php_pcs.lo] Error 1
ERROR: `make' failed
The command '/bin/sh -c pecl install pcs-1.3.3
```

**Comment by jefflaplante** [comment]
I have this same exact issue with php 7.4.6 on the official docker image.

**Comment by flaupretre** [comment]
OK. I'm working on the issue

**Comment by flaupretre** [comment]
Need to fix tests

**Comment by josev814** [comment]
I tried running all of the unit tests, and only php 5.6 was passing on Travis CI.  I had it test against 5.6-7.4 and nightly.

**Comment by GrahamCampbell** [comment]
Is this issue present in the corresponding PHP 7.3 release too, or just the 7.4 branch. If it is, then the fix in the codebase won't be enough.

**Comment by josev814** [comment]
From what I saw in php 7.3 it would install, but would result in a segfault doing php -a or running pecl list after enabling it.

**Comment by flaupretre** [comment]
OK. Thanks for the information. I will check it all starting with 5.6.

**Comment by flaupretre** [comment]
Everything seems to be OK now.
